project:
  type: website
  output-dir: docs

website:
  title: "R. Dal Ben"
  navbar:
    left:
      - text: ""
#        href: index.qmd
#      - text: "Portfolio"
#        href: portfolio/index.qmd
#      - text: "Publications"
#        href: publications/index.qmd
#      - text: "CV"
#        href: cv/index.qmd
  search: false  # Hidden for now, can be enabled later when site grows

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
